fix: fix issue #6
bearcatsdev/adab-android pull request #7
Opened 2020-08-06 10:22 UTC by developerchan1

I have fixed the problem related to issue #6

2020-08-06 11:14 UTC, werdna521 requested changes
Hi @developerchan1 I guess your code should be working fine now. However, I noticed that you did change a lot of code just to fix a date format problem. That is a clue that the code is redundant and unclean. Would you please refactor the code by creating a util class or a mixin so that if we have to change the format in the future, a one-liner change will be enough.

2020-08-06 12:05 UTC, developerchan1 commented
Okay, I will try to make the code more DRY

2020-08-06 15:01 UTC, developerchan1 commented
@werdna521, I have made many changes. Please recheck my commit. Thanks

2020-08-06 15:33 UTC, angsanley approved these changes

2020-08-06 17:42 UTC, werdna521 approved these changes

2020-08-07 00:52 UTC, brainwo approved these changes

2020-08-07 09:31 UTC, merged